_prefs: 
  baselayer: ''
  mapid: skorasaurus.5eb85050
  saveCenter: true
_properties: 
  bridge: 
    "group-by": layer
attribution: Map data © OpenStreetMap contributors
bounds: 
  - -180
  - -85.0511
  - 180
  - 85.0511
center: 
  - -81.68805956840515
  - 41.49788670055953
  - 17
description: 'a muted background tile layer for a basemap, using pastels; minimal POI and place labels; with Road labels. '
format: "png8:m=h"
interactivity_layer: ''
layers: null
maxzoom: 21
minzoom: 13
name: pastel_pascal
source: "mapbox:///mapbox.mapbox-streets-v5"
styles: 
  - style.mss
  - road.mss
  - labels.mss
template: ''
